/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/database.types`; params?: Router.UnknownInputParams; } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/random`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Screen`; params?: Router.UnknownInputParams; } | { pathname: `/services/Service`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/useSupabase`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/database.types`; params?: Router.UnknownOutputParams; } | { pathname: `/config`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/random`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Screen`; params?: Router.UnknownOutputParams; } | { pathname: `/services/Service`; params?: Router.UnknownOutputParams; } | { pathname: `/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/contexts/useSupabase`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/database.types${`?${string}` | `#${string}` | ''}` | `/config${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/random${`?${string}` | `#${string}` | ''}` | `/navigation/navigation${`?${string}` | `#${string}` | ''}` | `/screens/Screen${`?${string}` | `#${string}` | ''}` | `/services/Service${`?${string}` | `#${string}` | ''}` | `/theme${`?${string}` | `#${string}` | ''}` | `/contexts/useSupabase${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/database.types`; params?: Router.UnknownInputParams; } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/random`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Screen`; params?: Router.UnknownInputParams; } | { pathname: `/services/Service`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/useSupabase`; params?: Router.UnknownInputParams; };
    }
  }
}
